[build]
builder = "dockerfile"
dockerfilePath = "code/frontend/Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[service]
internalPort = 3000
